### ISSUE TITLE
Why use LiteLLM proxy vs. sdk 

### ISSUE THREAD

**Issue by krrishdholakia** [merlinn-co/merlinn#14]
Hey @david1542, cool project! 

Saw you're using litellm proxy - curious why do it that way vs. just using the sdk? 

- LiteLLM Maintainer

**Comment by david1542** [comment]
Hi @krrishdholakia, that's a good question. We wanted to keep our langchain & llama-index code untouched and smoothly allow users to define their own chat & embedding models. By doing this, we wanted to make the code super agnostic.

The places in which we do these things are in the `services/api/src/agent` and `services/data-processor/src/build.py`.

Do you think a better way is to drop the proxy and switch to LiteLLM sdk directly?

**Comment by david1542** [comment]
@krrishdholakia I'm closing this for now. I hope I've answered your question 🙏
