### ISSUE TITLE
Unable to start docker after first 5 steps of installation guide 

### ISSUE THREAD

**Issue by sraibagiwith100x** [merlinn-co/merlinn#16]
I have configured the open ai and slack configs as specified, haven't enabled any integrations, wanted to just see the dashboard once

but the docker compose fails 

(.venv) ➜  merlinn git:(main) docker compose up -d
service "data-processor-common" can't be used with `extends` as it declare `depends_on`

**Comment by david1542** [comment]
Hi @sraibagiwith100x thx for filing this issue. Seems like there was a recent discussion on this issue [here](https://github.com/docker/compose/issues/11544).

Can you try to upgrade your docker compose to the latest version?

**Comment by david1542** [comment]
I'm closing this issue for now, since it's most likely due to a docker compose version issue (posted information about it in the [previous](https://github.com/merlinn-co/merlinn/issues/16#issuecomment-2247393762) comment).
