### ISSUE TITLE
Share video with integration different of slack

### ISSUE THREAD

**Issue by johnfelipe** [merlinn-co/merlinn#24]
Hi team
Can u share us videos with integration different of slack, for example Jira, confluence
Tnks

**Comment by david1542** [comment]
Hi @johnfelipe, yeah we can do that. Do you have a specific use-case in mind, though? Are you referring to the knowledge-base integration? Namely, the ability to ingest data from Jira/Confluence.

**Comment by johnfelipe** [comment]
I want to review with grafana, Jira/confluence
Tnks.

**Comment by johnfelipe** [comment]
I have a lot of data in grafana, may be this app help me for insight and give me alerts when something happens.

And Jira/confluence to 
Pls share me that video because is important before, I know this is app I need but for report to stakeholders I need a good video demonstration

**Comment by david1542** [comment]
Hi @johnfelipe, can you please describe a scenario that you want us to record? It'd be amazing to delve into specifics. If you can outline what exactly would you like to see, that would be great.

For example:
1. Connect Grafana, Jira & Confluence
2. Receive alert from Grafana 
3. Perform an analysis of the alert and send findings to Slack.

I'm still not 100% what is your use-case. Can you please elaborate a bit more?
Alternatively, we can schedule a short call and I'd be happy to show you. If you're down, please email support@merlinn.co

**Comment by david1542** [comment]
Hi @johnfelipe do you mind sending me a DM in our [Slack](https://join.slack.com/t/merlinncommunity/shared_invite/zt-2le6bbavn-1WMwsPU5noECPyV9nQ8h4g)? I'd love to talk to you there and understand your use case better.
