### ISSUE TITLE
Support configurable OpenAI endpoint

### ISSUE THREAD

**Issue by lenaxia** [merlinn-co/merlinn#5]
**Description:**
Being able to use other endpoints will greatly help with adoption and flexibility on the users end. OpenAI compatible endpoints are abundant in both self hosted and enterprise solution. Just being able to define such an endpoint would allow usage of services like AWS Bedrock (via LiteLLM), and LocalAI. 

**Ask:**
* Allow defining a `OPENAI_ENDPOINT` or some similar configurable environment variable along the API token.

**Comment by david1542** [comment]
Hi @lenaxia , thanks for creating this issue. We're indeed working on this ability, and we'll here once it's released. Thanks again for filing this issue!

**Comment by david1542** [comment]
Hi @lenaxia,

Just updating that we've released the support for other vendors using LiteLLM :) We've added instructions on how to setup that in the [quickstart guide](https://github.com/merlinn-co/merlinn?tab=readme-ov-file#quick-installation-%EF%B8%8F).
