### ISSUE TITLE
Can u share RCA demo 

### ISSUE THREAD

**Issue by johnfelipe** [merlinn-co/merlinn#7]
Is possible connect with JIRA?

**Comment by david1542** [comment]
Hi @johnfelipe,
You can checkout our demo video [here](https://github.com/merlinn-co/merlinn?tab=readme-ov-file#demo-).

Moreover, we do support JIRA. The integration with JIRA allows us to ingest tickets and other information from JIRA, which we use during incidents. Checkout our documentation page [here](https://docs.merlinn.co/Integrations/Jira).

**Comment by johnfelipe** [comment]
Can you pls share a video with RCA supported by AI, pls...

**Comment by david1542** [comment]
Hi @johnfelipe :) I've shared with you our official demo at the comment above.

You can find our other demo video (with Grafana) [here](https://www.loom.com/share/efcd8eb42688406eb3d8f01dc5043938?sid=b91b32e5-97d1-4885-87a9-f5d9d5fd6315)

**Comment by johnfelipe** [comment]
Is possible in locally installation have demo content, my need is with RCA
AI generated...

**Comment by david1542** [comment]
@johnfelipe Yes, you can run Merlinn locally and connect it to your production system and test it out.
You'd just need to connect your tools (DataDog/Coralogix/Grafana) to your local setup and use the tool. I hope this helps.

If you want more information or guidance, feel free to reach out on our [Slack community](https://join.slack.com/t/merlinncommunity/shared_invite/zt-2le6bbavn-1WMwsPU5noECPyV9nQ8h4g).

**Comment by david1542** [comment]
Closing this for now :) If you have more questions, feel free to create a new issue or send us a message in the Slack community 😊
